version: '3.2'

services:
  db:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ")UiCMCiWRcee9Yg"
      POSTGRES_USER: lbryweb
  daemon:
    image: sayplastic/lbrynet:latest
    ports:
      - "5479:5279"
    volumes:
      - type: bind
        source: ./.daemon_test_local_storage
        target: /storage
  app:
    # image: sayplastic/lbryweb-prototype
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
      - daemon
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: lbryweb
      LBRY_DAEMON: http://daemon:5279/
      LBRY_DOWNLOAD_DIRECTORY: /storage/download
      LBRY_PUBLISH_SAVE: /storage/publish
      LBRY_PUBLISH_FEED: /storage/publish
    volumes:
    #   - ./lbryweb:/app/lbryweb
      - type: bind
        source: ./.daemon_test_local_storage
        target: /storage
        volume:
          nocopy: true

volumes:
  storage:
