version: '3.2'

services:
  db:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ")UiCMCiWRcee9Yg"
      POSTGRES_USER: lbryweb
  daemon:
    image: sayplastic/lbrynet:0.30.1rc1
    ports:
      - "5479:5279"
    volumes:
      - type: bind
        source: ./.daemon_test_local_storage
        target: /storage
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - daemon
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: lbryweb
      LBRY_DAEMON: http://daemon:5279/
      LBRY_DOWNLOAD_DIRECTORY: /storage/download
    volumes:
      - ./lbryweb:/app/lbryweb
      - type: bind
        source: ./.daemon_test_local_storage
        target: /storage
        volume:
          nocopy: true

volumes:
  storage:
